DROP TABLE IF EXISTS `chatroom`;

CREATE TABLE IF NOT EXISTS `chatroom` (
`id` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`message` int(10) NOT NULL,
`from` int(10) NOT NULL,
`to` int(10) NOT NULL,
`read` boolean NOT NULL,
`mute_noti` boolean NOT NULL,
`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`create_by` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `chatroom` 
    ADD FOREIGN KEY (`message`) REFERENCES `message`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`from`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`to`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`create_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;