DROP TABLE IF EXISTS `classchat`;

CREATE TABLE IF NOT EXISTS `classchat` (
`id` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`message` int(10) NOT NULL,
`class` int(10) NOT NULL,
`to` int(10) NOT NULL,
`read` boolean NOT NULL,
`mute_noti` boolean NOT NULL,
`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`create_by` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `classchat` 
    ADD FOREIGN KEY (`message`) REFERENCES `message`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`class`) REFERENCES `class`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`to`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`create_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;