DROP TABLE IF EXISTS `comment`;

CREATE TABLE IF NOT EXISTS `comment` (
`id` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`pic_url` text,
`text` text NOT NULL,
`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`create_by` int(10) NOT NULL,
`update_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_by` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

ALTER TABLE `comment` 
    ADD FOREIGN KEY (`create_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`update_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;