DROP TABLE IF EXISTS `material`;

CREATE TABLE IF NOT EXISTS `material` (
`id` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`topic_name` int(10) NOT NULL,
`material_url` text NOT NULL,
`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`create_by` int(10) NOT NULL,
`update_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_by` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `material` 
    ADD FOREIGN KEY (`topic_name`) REFERENCES `material_topic`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`create_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`update_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;