DROP TABLE IF EXISTS `material_topic`;

CREATE TABLE IF NOT EXISTS `material_topic` (
`id` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`title` varchar(250) NOT NULL,
`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`create_by` int(10) NOT NULL,
`update_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_by` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `material_topic` 
    ADD FOREIGN KEY (`create_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`update_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;