DROP TABLE IF EXISTS `poll`;

CREATE TABLE IF NOT EXISTS `poll` (
`id` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`option` int(10) NOT NULL,
`result` int(10) NOT NULL,
`expired` DATETIME,
`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`create_by` int(10) NOT NULL,
`update_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_by` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

ALTER TABLE `poll` 
    ADD FOREIGN KEY (`option`) REFERENCES `poll_option`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`result`) REFERENCES `poll_result`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`create_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY (`update_by`) REFERENCES `account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;